steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/datasets:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/datasets:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'datasets'
      - '--image=gcr.io/$PROJECT_ID/datasets:$COMMIT_SHA'
      - '--region=europe-west4'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--cpu=1'
      - '--memory=2Gi'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=POSTGRES_URI=${_POSTGRES_URI},AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID},AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY},AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION},LANGCHAIN_API_KEY=${_LANGCHAIN_API_KEY}'
      - '--set-env-vars=USE_EXPLICIT_GRAPH=true,DATASET_AGENT_URL=/agent'
      - '--add-volume=name=gcs,type=cloud-storage,bucket=mixture-othertales-co'
      - '--add-volume-mount=volume=gcs,mount-path=/gcs'
      
images:
  - 'gcr.io/$PROJECT_ID/datasets:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
